version: "3.5"

services:
  pg:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: foodcourt
      POSTGRES_USER: project
      POSTGRES_PASSWORD: pasSwo0rd
  foodcourt-dev:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/var/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - pg