# Generated by Django 3.2 on 2021-04-17 18:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_cost', models.FloatField(default=0)),
                ('count_persons', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('address', models.TextField()),
                ('food', models.ManyToManyField(to='food.Food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
