"""create models

Revision ID: b32626f8837e
Revises: 
Create Date: 2021-04-11 15:50:28.733299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32626f8837e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), server_default='', nullable=False),
    sa.Column('cost', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts_create', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('item_list', sa.String(), nullable=True),
    sa.Column('address', sa.String(), server_default='', nullable=False),
    sa.Column('count_person', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('menu')
    # ### end Alembic commands ###
