# Generated by Django 3.2 on 2021-04-17 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=256)),
                ('ts_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('auth_token', models.CharField(blank=True, max_length=36, unique=True)),
                ('auth_expired', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
